spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cts
    username: postgres
    password: Rajeev@2345
    
  jpa:    show-sql: true
    hibernate:      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect